#!/bin/bash

pandoc Manual-EDIT-Platform-04-Working-with-the-TaxEditor.md -f markdown --pdf-engine=xelatex  -V 'mainfont:Arial Unicode MS' -V geometry:a4paper  -V geometry:margin=2cm \
     --toc  --number-sections \
     --template=../templates/eisvogel-2.0.0/eisvogel.latex \
     -V date:$(date -I) \
     -o Manual-EDIT-Platform-04-Working-with-the-TaxEditor.pdf
